import 'package:flutter/material.dart' hide Text;

import 'app_localizations.dart';
import 'bloom.dart';
import 'src/rust/api/ai.dart';
import 'src/rust/api/book.dart';
import 'theme.dart';

/// Per-book data generated by local AI.
///
/// This is intentionally separate from general settings: summaries, moods and
/// semantic indexes belong to the AI feature that created them. They are all
/// derived data and can be rebuilt without touching books or reading history.
class AiCachePage extends StatefulWidget {
  final ReadingSettings settings;

  const AiCachePage({super.key, required this.settings});

  @override
  State<AiCachePage> createState() => _AiCachePageState();
}

class _AiCachePageState extends State<AiCachePage> {
  CacheUsage? _usage;
  String? _error;
  int? _busy;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      final usage = await cacheUsage();
      if (mounted) {
        setState(() {
          _usage = usage;
          _error = null;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _error = '$e');
    }
  }

  Future<bool> _confirm(ReadingTheme t, String title) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: t.background,
        title: Text(title, style: TextStyle(color: t.text, fontSize: 16)),
        content: Text(
          '只会删除可重新生成的 AI 数据，不会删除小说文件或阅读记录。',
          style: TextStyle(color: t.muted, fontSize: 13, height: 1.5),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text('取消', style: TextStyle(color: t.muted)),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('删除', style: TextStyle(color: Color(0xFFB3574D))),
          ),
        ],
      ),
    );
    return ok ?? false;
  }

  Future<void> _clearBook(
    ReadingTheme t,
    CacheEntry book, {
    required bool all,
    bool summaries = false,
  }) async {
    final what = all
        ? '全部 AI 生成数据'
        : summaries
        ? '摘要与氛围'
        : '语义索引';
    if (!await _confirm(t, '删除《${book.title}》的$what？')) return;

    setState(() => _busy = book.bookId);
    try {
      if (all) {
        await dropBookCache(bookId: book.bookId);
      } else if (summaries) {
        await dropSummaries(bookId: book.bookId);
      } else {
        await dropIndex(bookId: book.bookId);
      }
      await _load();
    } catch (e) {
      if (mounted) setState(() => _error = '$e');
    } finally {
      if (mounted) setState(() => _busy = null);
    }
  }

  @override
  Widget build(BuildContext context) {
    final t = widget.settings.theme;
    return Scaffold(
      backgroundColor: t.background,
      appBar: AppBar(
        backgroundColor: t.background,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        iconTheme: IconThemeData(color: t.muted),
        title: Text('AI 生成数据', style: TextStyle(color: t.text, fontSize: 17)),
      ),
      body: RefreshIndicator(
        onRefresh: _load,
        child: ListView(
          physics: const AlwaysScrollableScrollPhysics(),
          padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
          children: [
            Text(
              '管理本地模型为每本书生成的摘要、氛围和语义索引。'
              '这些内容都可以重新生成，小说原文与阅读记录不会出现在这里。',
              style: TextStyle(color: t.muted, fontSize: 13, height: 1.6),
            ),
            const SizedBox(height: 20),
            if (_error != null) _errorCard(t),
            if (_usage == null && _error == null)
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 40),
                child: Center(child: Bloom(color: t.muted, size: 34)),
              )
            else if (_usage != null) ...[
              Row(
                children: [
                  Text(
                    '按书管理',
                    style: TextStyle(
                      color: t.text,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  const Spacer(),
                  Text(
                    '数据库 ${_formatBytes(_usage!.dbBytes)}',
                    style: TextStyle(color: t.muted, fontSize: 11),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              if (_usage!.books.isEmpty)
                _empty(t)
              else
                for (final book in _usage!.books) _bookTile(t, book),
            ],
          ],
        ),
      ),
    );
  }

  Widget _errorCard(ReadingTheme t) => Container(
    margin: const EdgeInsets.only(bottom: 16),
    padding: const EdgeInsets.all(12),
    decoration: BoxDecoration(
      color: const Color(0xFFB3574D).withValues(alpha: 0.08),
      borderRadius: BorderRadius.circular(8),
    ),
    child: Row(
      children: [
        const Icon(Icons.error_outline, color: Color(0xFFB3574D), size: 18),
        const SizedBox(width: 10),
        Expanded(
          child: Text(_error!, style: TextStyle(color: t.text, fontSize: 12)),
        ),
        TextButton(onPressed: _load, child: const Text('重试')),
      ],
    ),
  );

  Widget _empty(ReadingTheme t) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 32),
    child: Column(
      children: [
        Icon(
          Icons.auto_awesome_outlined,
          color: t.muted.withValues(alpha: 0.65),
          size: 30,
        ),
        const SizedBox(height: 10),
        Text('还没有生成任何 AI 数据', style: TextStyle(color: t.muted, fontSize: 13)),
      ],
    ),
  );

  Widget _bookTile(ReadingTheme t, CacheEntry book) {
    final bytes = book.summaryBytes + book.chunkBytes;
    final empty = book.summaries == 0 && book.chunks == 0;
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.fromLTRB(12, 10, 6, 10),
      decoration: BoxDecoration(
        border: Border.all(color: t.muted.withValues(alpha: 0.18)),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  book.title,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(color: t.text, fontSize: 13),
                ),
                const SizedBox(height: 3),
                Text(
                  empty
                      ? '暂无 AI 生成数据'
                      : '摘要 ${book.summaries}/${book.chapterCount} 章'
                            ' · 索引 ${book.chunks} 段'
                            ' · ${_formatBytes(bytes.toInt())}',
                  style: TextStyle(color: t.muted, fontSize: 11),
                ),
              ],
            ),
          ),
          if (_busy == book.bookId)
            Padding(
              padding: const EdgeInsets.only(right: 10),
              child: Bloom(color: t.muted, size: 18),
            )
          else if (!empty)
            PopupMenuButton<String>(
              tooltip: context.tr('管理 AI 数据'),
              icon: Icon(Icons.more_horiz, color: t.muted, size: 20),
              color: t.background,
              onSelected: (value) => _clearBook(
                t,
                book,
                all: value == 'all',
                summaries: value == 'summaries',
              ),
              itemBuilder: (_) => [
                if (book.summaries > 0)
                  PopupMenuItem(
                    value: 'summaries',
                    child: Text(
                      '删除摘要与氛围',
                      style: TextStyle(color: t.text, fontSize: 13),
                    ),
                  ),
                if (book.chunks > 0)
                  PopupMenuItem(
                    value: 'index',
                    child: Text(
                      '删除语义索引',
                      style: TextStyle(color: t.text, fontSize: 13),
                    ),
                  ),
                PopupMenuItem(
                  value: 'all',
                  child: Text(
                    '全部删除',
                    style: TextStyle(color: t.text, fontSize: 13),
                  ),
                ),
              ],
            ),
        ],
      ),
    );
  }
}

String _formatBytes(int bytes) {
  if (bytes <= 0) return '0 B';
  if (bytes < 1024) return '$bytes B';
  if (bytes < 1024 * 1024) {
    return '${(bytes / 1024).toStringAsFixed(0)} KB';
  }
  return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
}
