// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/book.dart';
import 'api/simple.dart';
import 'api/source.dart';
import 'api/tts.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DescribeProgress> dco_decode_StreamSink_describe_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<DownloadProgress> dco_decode_StreamSink_download_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<EnrichProgress> dco_decode_StreamSink_enrich_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<IndexProgress> dco_decode_StreamSink_index_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<OfferProbe> dco_decode_StreamSink_offer_probe_Sse(dynamic raw);

  @protected
  RustStreamSink<RelabelProgress> dco_decode_StreamSink_relabel_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SearchFeed> dco_decode_StreamSink_search_feed_Sse(dynamic raw);

  @protected
  RustStreamSink<TestFeed> dco_decode_StreamSink_test_feed_Sse(dynamic raw);

  @protected
  RustStreamSink<VetProgress> dco_decode_StreamSink_vet_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiDeviceState dco_decode_ai_device_state(dynamic raw);

  @protected
  AiRuntimeConfig dco_decode_ai_runtime_config(dynamic raw);

  @protected
  AiStatus dco_decode_ai_status(dynamic raw);

  @protected
  BookAnnotation dco_decode_book_annotation(dynamic raw);

  @protected
  BookInfo dco_decode_book_info(dynamic raw);

  @protected
  BookTime dco_decode_book_time(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  CacheEntry dco_decode_cache_entry(dynamic raw);

  @protected
  CacheUsage dco_decode_cache_usage(dynamic raw);

  @protected
  CastGraph dco_decode_cast_graph(dynamic raw);

  @protected
  CastPerson dco_decode_cast_person(dynamic raw);

  @protected
  CastRelation dco_decode_cast_relation(dynamic raw);

  @protected
  ChapterInfo dco_decode_chapter_info(dynamic raw);

  @protected
  DescribeProgress dco_decode_describe_progress(dynamic raw);

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw);

  @protected
  EnrichProgress dco_decode_enrich_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FoundBookItem dco_decode_found_book_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IndexProgress dco_decode_index_progress(dynamic raw);

  @protected
  IndexStatus dco_decode_index_status(dynamic raw);

  @protected
  Landmine dco_decode_landmine(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookAnnotation> dco_decode_list_book_annotation(dynamic raw);

  @protected
  List<BookTime> dco_decode_list_book_time(dynamic raw);

  @protected
  List<CacheEntry> dco_decode_list_cache_entry(dynamic raw);

  @protected
  List<CastPerson> dco_decode_list_cast_person(dynamic raw);

  @protected
  List<CastRelation> dco_decode_list_cast_relation(dynamic raw);

  @protected
  List<ChapterInfo> dco_decode_list_chapter_info(dynamic raw);

  @protected
  List<FoundBookItem> dco_decode_list_found_book_item(dynamic raw);

  @protected
  List<Landmine> dco_decode_list_landmine(dynamic raw);

  @protected
  List<Offer> dco_decode_list_offer(dynamic raw);

  @protected
  List<Paragraph> dco_decode_list_paragraph(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadingEvent> dco_decode_list_reading_event(dynamic raw);

  @protected
  List<RelEvidence> dco_decode_list_rel_evidence(dynamic raw);

  @protected
  List<RelationshipEvidenceInfo> dco_decode_list_relationship_evidence_info(
    dynamic raw,
  );

  @protected
  List<RelationshipPersonInfo> dco_decode_list_relationship_person_info(
    dynamic raw,
  );

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw);

  @protected
  List<ShelfItem> dco_decode_list_shelf_item(dynamic raw);

  @protected
  List<SourceItem> dco_decode_list_source_item(dynamic raw);

  @protected
  List<VolumeInfo> dco_decode_list_volume_info(dynamic raw);

  @protected
  Offer dco_decode_offer(dynamic raw);

  @protected
  OfferProbe dco_decode_offer_probe(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  List<SearchHit>? dco_decode_opt_list_search_hit(dynamic raw);

  @protected
  ParaKind dco_decode_para_kind(dynamic raw);

  @protected
  Paragraph dco_decode_paragraph(dynamic raw);

  @protected
  ReadingEvent dco_decode_reading_event(dynamic raw);

  @protected
  RelEvidence dco_decode_rel_evidence(dynamic raw);

  @protected
  RelabelProgress dco_decode_relabel_progress(dynamic raw);

  @protected
  RelationshipEvidenceInfo dco_decode_relationship_evidence_info(dynamic raw);

  @protected
  RelationshipPersonInfo dco_decode_relationship_person_info(dynamic raw);

  @protected
  RelationshipStructureInfo dco_decode_relationship_structure_info(dynamic raw);

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw);

  @protected
  SearchFeed dco_decode_search_feed(dynamic raw);

  @protected
  SearchHit dco_decode_search_hit(dynamic raw);

  @protected
  ShelfItem dco_decode_shelf_item(dynamic raw);

  @protected
  SourceItem dco_decode_source_item(dynamic raw);

  @protected
  SourceTest dco_decode_source_test(dynamic raw);

  @protected
  TestFeed dco_decode_test_feed(dynamic raw);

  @protected
  TtsStatus dco_decode_tts_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VetProgress dco_decode_vet_progress(dynamic raw);

  @protected
  VolumeInfo dco_decode_volume_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DescribeProgress> sse_decode_StreamSink_describe_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DownloadProgress> sse_decode_StreamSink_download_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<EnrichProgress> sse_decode_StreamSink_enrich_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<IndexProgress> sse_decode_StreamSink_index_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<OfferProbe> sse_decode_StreamSink_offer_probe_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RelabelProgress> sse_decode_StreamSink_relabel_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SearchFeed> sse_decode_StreamSink_search_feed_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TestFeed> sse_decode_StreamSink_test_feed_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<VetProgress> sse_decode_StreamSink_vet_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiDeviceState sse_decode_ai_device_state(SseDeserializer deserializer);

  @protected
  AiRuntimeConfig sse_decode_ai_runtime_config(SseDeserializer deserializer);

  @protected
  AiStatus sse_decode_ai_status(SseDeserializer deserializer);

  @protected
  BookAnnotation sse_decode_book_annotation(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer);

  @protected
  BookTime sse_decode_book_time(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  CacheEntry sse_decode_cache_entry(SseDeserializer deserializer);

  @protected
  CacheUsage sse_decode_cache_usage(SseDeserializer deserializer);

  @protected
  CastGraph sse_decode_cast_graph(SseDeserializer deserializer);

  @protected
  CastPerson sse_decode_cast_person(SseDeserializer deserializer);

  @protected
  CastRelation sse_decode_cast_relation(SseDeserializer deserializer);

  @protected
  ChapterInfo sse_decode_chapter_info(SseDeserializer deserializer);

  @protected
  DescribeProgress sse_decode_describe_progress(SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer);

  @protected
  EnrichProgress sse_decode_enrich_progress(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FoundBookItem sse_decode_found_book_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IndexProgress sse_decode_index_progress(SseDeserializer deserializer);

  @protected
  IndexStatus sse_decode_index_status(SseDeserializer deserializer);

  @protected
  Landmine sse_decode_landmine(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookAnnotation> sse_decode_list_book_annotation(
    SseDeserializer deserializer,
  );

  @protected
  List<BookTime> sse_decode_list_book_time(SseDeserializer deserializer);

  @protected
  List<CacheEntry> sse_decode_list_cache_entry(SseDeserializer deserializer);

  @protected
  List<CastPerson> sse_decode_list_cast_person(SseDeserializer deserializer);

  @protected
  List<CastRelation> sse_decode_list_cast_relation(
    SseDeserializer deserializer,
  );

  @protected
  List<ChapterInfo> sse_decode_list_chapter_info(SseDeserializer deserializer);

  @protected
  List<FoundBookItem> sse_decode_list_found_book_item(
    SseDeserializer deserializer,
  );

  @protected
  List<Landmine> sse_decode_list_landmine(SseDeserializer deserializer);

  @protected
  List<Offer> sse_decode_list_offer(SseDeserializer deserializer);

  @protected
  List<Paragraph> sse_decode_list_paragraph(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadingEvent> sse_decode_list_reading_event(
    SseDeserializer deserializer,
  );

  @protected
  List<RelEvidence> sse_decode_list_rel_evidence(SseDeserializer deserializer);

  @protected
  List<RelationshipEvidenceInfo> sse_decode_list_relationship_evidence_info(
    SseDeserializer deserializer,
  );

  @protected
  List<RelationshipPersonInfo> sse_decode_list_relationship_person_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer);

  @protected
  List<ShelfItem> sse_decode_list_shelf_item(SseDeserializer deserializer);

  @protected
  List<SourceItem> sse_decode_list_source_item(SseDeserializer deserializer);

  @protected
  List<VolumeInfo> sse_decode_list_volume_info(SseDeserializer deserializer);

  @protected
  Offer sse_decode_offer(SseDeserializer deserializer);

  @protected
  OfferProbe sse_decode_offer_probe(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  List<SearchHit>? sse_decode_opt_list_search_hit(SseDeserializer deserializer);

  @protected
  ParaKind sse_decode_para_kind(SseDeserializer deserializer);

  @protected
  Paragraph sse_decode_paragraph(SseDeserializer deserializer);

  @protected
  ReadingEvent sse_decode_reading_event(SseDeserializer deserializer);

  @protected
  RelEvidence sse_decode_rel_evidence(SseDeserializer deserializer);

  @protected
  RelabelProgress sse_decode_relabel_progress(SseDeserializer deserializer);

  @protected
  RelationshipEvidenceInfo sse_decode_relationship_evidence_info(
    SseDeserializer deserializer,
  );

  @protected
  RelationshipPersonInfo sse_decode_relationship_person_info(
    SseDeserializer deserializer,
  );

  @protected
  RelationshipStructureInfo sse_decode_relationship_structure_info(
    SseDeserializer deserializer,
  );

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer);

  @protected
  SearchFeed sse_decode_search_feed(SseDeserializer deserializer);

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer);

  @protected
  ShelfItem sse_decode_shelf_item(SseDeserializer deserializer);

  @protected
  SourceItem sse_decode_source_item(SseDeserializer deserializer);

  @protected
  SourceTest sse_decode_source_test(SseDeserializer deserializer);

  @protected
  TestFeed sse_decode_test_feed(SseDeserializer deserializer);

  @protected
  TtsStatus sse_decode_tts_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VetProgress sse_decode_vet_progress(SseDeserializer deserializer);

  @protected
  VolumeInfo sse_decode_volume_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_describe_progress_Sse(
    RustStreamSink<DescribeProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_progress_Sse(
    RustStreamSink<DownloadProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_enrich_progress_Sse(
    RustStreamSink<EnrichProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_index_progress_Sse(
    RustStreamSink<IndexProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_offer_probe_Sse(
    RustStreamSink<OfferProbe> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_relabel_progress_Sse(
    RustStreamSink<RelabelProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
    RustStreamSink<ScanProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_search_feed_Sse(
    RustStreamSink<SearchFeed> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_test_feed_Sse(
    RustStreamSink<TestFeed> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_vet_progress_Sse(
    RustStreamSink<VetProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_device_state(AiDeviceState self, SseSerializer serializer);

  @protected
  void sse_encode_ai_runtime_config(
    AiRuntimeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_status(AiStatus self, SseSerializer serializer);

  @protected
  void sse_encode_book_annotation(
    BookAnnotation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_book_time(BookTime self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_cache_entry(CacheEntry self, SseSerializer serializer);

  @protected
  void sse_encode_cache_usage(CacheUsage self, SseSerializer serializer);

  @protected
  void sse_encode_cast_graph(CastGraph self, SseSerializer serializer);

  @protected
  void sse_encode_cast_person(CastPerson self, SseSerializer serializer);

  @protected
  void sse_encode_cast_relation(CastRelation self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_info(ChapterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_describe_progress(
    DescribeProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_progress(
    DownloadProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enrich_progress(
    EnrichProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_found_book_item(FoundBookItem self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_index_progress(IndexProgress self, SseSerializer serializer);

  @protected
  void sse_encode_index_status(IndexStatus self, SseSerializer serializer);

  @protected
  void sse_encode_landmine(Landmine self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_annotation(
    List<BookAnnotation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_time(List<BookTime> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cache_entry(
    List<CacheEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cast_person(
    List<CastPerson> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cast_relation(
    List<CastRelation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chapter_info(
    List<ChapterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_found_book_item(
    List<FoundBookItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_landmine(List<Landmine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_offer(List<Offer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_paragraph(
    List<Paragraph> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reading_event(
    List<ReadingEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rel_evidence(
    List<RelEvidence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relationship_evidence_info(
    List<RelationshipEvidenceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relationship_person_info(
    List<RelationshipPersonInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shelf_item(
    List<ShelfItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_item(
    List<SourceItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_volume_info(
    List<VolumeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_offer(Offer self, SseSerializer serializer);

  @protected
  void sse_encode_offer_probe(OfferProbe self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_search_hit(
    List<SearchHit>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_para_kind(ParaKind self, SseSerializer serializer);

  @protected
  void sse_encode_paragraph(Paragraph self, SseSerializer serializer);

  @protected
  void sse_encode_reading_event(ReadingEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rel_evidence(RelEvidence self, SseSerializer serializer);

  @protected
  void sse_encode_relabel_progress(
    RelabelProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relationship_evidence_info(
    RelationshipEvidenceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relationship_person_info(
    RelationshipPersonInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relationship_structure_info(
    RelationshipStructureInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer);

  @protected
  void sse_encode_search_feed(SearchFeed self, SseSerializer serializer);

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_shelf_item(ShelfItem self, SseSerializer serializer);

  @protected
  void sse_encode_source_item(SourceItem self, SseSerializer serializer);

  @protected
  void sse_encode_source_test(SourceTest self, SseSerializer serializer);

  @protected
  void sse_encode_test_feed(TestFeed self, SseSerializer serializer);

  @protected
  void sse_encode_tts_status(TtsStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vet_progress(VetProgress self, SseSerializer serializer);

  @protected
  void sse_encode_volume_info(VolumeInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
