// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `after_think`, `ai_dir`, `background_rest`, `build_portrait_facts`, `chat_once`, `classify_mood`, `clean_summary`, `compose`, `dechunk`, `dir_bytes`, `embed_child`, `embed`, `engine_child`, `engine_context`, `engine_files`, `ensure_embedder_with`, `ensure_embedder`, `ensure_engine`, `ensure`, `file_bytes`, `find_engine`, `find_gguf`, `find_model`, `fmt_dur`, `health`, `hour_bucket`, `http`, `is_a_person`, `is_embed_model`, `kill_port_holder`, `landmine_context_spans`, `landmine_context`, `landmine_queries`, `normalized_evidence`, `repeats_original`, `runtime_config`, `stop_chat_engine`, `summarize_excerpt`, `summarize_person`, `summarize_relation`, `tail_pick`, `ymd_from_epoch`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LastInputInfo`, `MemoryStatusEx`, `PortraitFacts`, `SystemPowerStatus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> setAiRuntimeConfig({
  required int mode,
  required int backend,
  required int threadLimit,
  required int thermalBias,
  required BigInt totalMemoryMb,
}) => RustLib.instance.api.crateApiAiSetAiRuntimeConfig(
  mode: mode,
  backend: backend,
  threadLimit: threadLimit,
  thermalBias: thermalBias,
  totalMemoryMb: totalMemoryMb,
);

Future<AiDeviceState> aiDeviceState() =>
    RustLib.instance.api.crateApiAiAiDeviceState();

/// Called once at startup with `<app-support>/ai`. Engine binaries and model
/// weights live there; the user can also drop files in by hand.
Future<void> initAi({required String dir}) =>
    RustLib.instance.api.crateApiAiInitAi(dir: dir);

Future<AiStatus> aiStatus() => RustLib.instance.api.crateApiAiAiStatus();

/// Delete an installed model. The engine holds the file open while it runs, so
/// stop it first — on Windows the delete simply fails otherwise.
///
/// Vectors already computed are left alone: they are still correct, and
/// re-installing the same model makes them usable again without re-indexing.
Future<void> deleteModel({required bool embed}) =>
    RustLib.instance.api.crateApiAiDeleteModel(embed: embed);

/// Delete the engine: the binary and everything that shipped with it, but never
/// a model — those are separate downloads with separate delete buttons.
Future<void> deleteEngine() => RustLib.instance.api.crateApiAiDeleteEngine();

Future<void> stopAi() => RustLib.instance.api.crateApiAiStopAi();

Future<void> cancelEnrich() => RustLib.instance.api.crateApiAiCancelEnrich();

/// Summarize every chapter of a book that has no summary yet, front to back,
/// streaming progress. Resumable by construction: finished chapters are on
/// disk, and a re-run only sees the missing ones.
Stream<EnrichProgress> enrichBook({
  required String path,
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiAiEnrichBook(path: path, bookId: bookId);

Future<void> cancelDescribe() =>
    RustLib.instance.api.crateApiAiCancelDescribe();

/// Write a background for every character in the graph, streaming each as it
/// lands. Same contract as [`label_relations`]: resumable, cancellable, and
/// whatever finished is on disk before the reader sees it.
Stream<DescribeProgress> describePeople({
  required String path,
  required PlatformInt64 bookId,
  required PlatformInt64 upToChapter,
}) => RustLib.instance.api.crateApiAiDescribePeople(
  path: path,
  bookId: bookId,
  upToChapter: upToChapter,
);

/// Throw away everything derived for this book's graph — the scan, the model's
/// verdicts on borderline names, and its relationship labels — so the next open
/// rebuilds from the text. The reader's 重置.
Future<void> forgetRelations({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiAiForgetRelations(bookId: bookId);

Future<void> cancelRelabel() => RustLib.instance.api.crateApiAiCancelRelabel();

/// Summarize every top edge up to the reader's chapter, streaming each as it
/// lands. Resumable within a run: cached pairs stream back instantly, and a
/// cancel leaves what is done in the cache for the next pass to keep.
Stream<RelabelProgress> labelRelations({
  required String path,
  required PlatformInt64 bookId,
  required PlatformInt64 upToChapter,
}) => RustLib.instance.api.crateApiAiLabelRelations(
  path: path,
  bookId: bookId,
  upToChapter: upToChapter,
);

Future<void> cancelVet() => RustLib.instance.api.crateApiAiCancelVet();

/// Rule on every borderline candidate the model has not seen yet, streaming each
/// verdict. Verdicts are written to the database as they land, so a cancelled
/// run keeps what it paid for.
Stream<VetProgress> vetNames({
  required String path,
  required PlatformInt64 bookId,
  required PlatformInt64 upToChapter,
}) => RustLib.instance.api.crateApiAiVetNames(
  path: path,
  bookId: bookId,
  upToChapter: upToChapter,
);

Future<IndexStatus> indexStatus({
  required String path,
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiAiIndexStatus(path: path, bookId: bookId);

Future<void> dropIndex({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiAiDropIndex(bookId: bookId);

/// Embed every chapter that has no vectors yet, front to back. Resumable by
/// construction, exactly like enrichment: what is on disk is done, and a re-run
/// after a crash or a cancel only sees what is left.
Future<void> cancelIndex() => RustLib.instance.api.crateApiAiCancelIndex();

Stream<IndexProgress> indexBook({
  required String path,
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiAiIndexBook(path: path, bookId: bookId);

/// Search the book — but only the part of it the reader has already read.
///
/// `up_to_chapter` is the spoiler line, and it is enforced in SQL: chapters
/// beyond it are never loaded, so no ranking bug can leak one. A reader who
/// searches for a character they have not met yet gets nothing, which is the
/// correct answer.
Future<List<SearchHit>> semanticSearch({
  required String path,
  required PlatformInt64 bookId,
  required String query,
  required PlatformInt64 upToChapter,
  required int k,
}) => RustLib.instance.api.crateApiAiSemanticSearch(
  path: path,
  bookId: bookId,
  query: query,
  upToChapter: upToChapter,
  k: k,
);

Future<List<Landmine>> landmines() =>
    RustLib.instance.api.crateApiAiLandmines();

/// Scan the **whole book**, not the part already read.
///
/// Every other retrieval path in this app is capped at the reader's current
/// chapter, and that cap is the reason none of them can spoil anything. Here it
/// is off on purpose: a warning about chapter 700 is worthless to someone
/// standing at chapter 1, and telling them anyway is the entire point of the
/// feature. It is why nothing calls this unless the reader taps it by name.
Stream<ScanProgress> scanLandmine({
  required String path,
  required PlatformInt64 bookId,
  required String id,
  required int k,
}) => RustLib.instance.api.crateApiAiScanLandmine(
  path: path,
  bookId: bookId,
  id: id,
  k: k,
);

/// A 阅读画像 paragraph, grounded entirely in counted facts. `angle` is a rotating
/// seed (advanced by 换一篇) that varies the phrasing; `tz_secs` is the reader's
/// UTC offset so session times and the opening date land on their local clock.
/// Pure template — no engine needed. Empty string when nothing has been read yet.
Future<String> readerPortrait({
  required int angle,
  required PlatformInt64 tzSecs,
}) =>
    RustLib.instance.api.crateApiAiReaderPortrait(angle: angle, tzSecs: tzSecs);

/// Platform facts used by the shared queue controller. Android and iOS will
/// provide these through their native adapters; Windows is implemented here so
/// the policy can be exercised before the mobile shells exist.
class AiDeviceState {
  final String platform;
  final bool? charging;
  final int? batteryPercent;
  final int? idleSeconds;
  final int logicalCores;
  final BigInt? totalMemoryMb;

  /// Windows has no dependable system-wide thermal state API. Mobile adapters
  /// will report nominal/fair/serious/critical here.
  final String thermalState;

  const AiDeviceState({
    required this.platform,
    this.charging,
    this.batteryPercent,
    this.idleSeconds,
    required this.logicalCores,
    this.totalMemoryMb,
    required this.thermalState,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      charging.hashCode ^
      batteryPercent.hashCode ^
      idleSeconds.hashCode ^
      logicalCores.hashCode ^
      totalMemoryMb.hashCode ^
      thermalState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiDeviceState &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          charging == other.charging &&
          batteryPercent == other.batteryPercent &&
          idleSeconds == other.idleSeconds &&
          logicalCores == other.logicalCores &&
          totalMemoryMb == other.totalMemoryMb &&
          thermalState == other.thermalState;
}

/// Cross-platform policy passed in by the Flutter layer. The UI owns persistence;
/// Rust owns the actual inference knobs. Keeping this contract free of Windows,
/// Android, or iOS types lets every platform feed the same queue later.
class AiRuntimeConfig {
  /// 0 = quiet, 1 = balanced, 2 = fast.
  final int mode;

  /// 0 = automatic, 1 = CPU only, 2 = GPU preferred.
  final int backend;

  /// Zero lets the engine choose a profile-derived ceiling.
  final int threadLimit;

  /// 0 = conservative, 1 = balanced, 2 = performance.
  final int thermalBias;

  /// Zero when the platform adapter cannot report physical memory.
  final BigInt totalMemoryMb;

  const AiRuntimeConfig({
    required this.mode,
    required this.backend,
    required this.threadLimit,
    required this.thermalBias,
    required this.totalMemoryMb,
  });

  static Future<AiRuntimeConfig> default_() =>
      RustLib.instance.api.crateApiAiAiRuntimeConfigDefault();

  @override
  int get hashCode =>
      mode.hashCode ^
      backend.hashCode ^
      threadLimit.hashCode ^
      thermalBias.hashCode ^
      totalMemoryMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRuntimeConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          backend == other.backend &&
          threadLimit == other.threadLimit &&
          thermalBias == other.thermalBias &&
          totalMemoryMb == other.totalMemoryMb;
}

class AiStatus {
  final String dir;
  final bool engine;
  final String? model;

  /// The embedding model, installed separately: semantic search needs it,
  /// summaries and moods do not. Absent is a normal state, not an error.
  final String? embedModel;

  /// Bytes on disk, so the page offering to delete something can say what it
  /// is worth deleting.
  final PlatformInt64 engineBytes;
  final PlatformInt64 modelBytes;
  final PlatformInt64 embedBytes;
  final bool running;

  const AiStatus({
    required this.dir,
    required this.engine,
    this.model,
    this.embedModel,
    required this.engineBytes,
    required this.modelBytes,
    required this.embedBytes,
    required this.running,
  });

  @override
  int get hashCode =>
      dir.hashCode ^
      engine.hashCode ^
      model.hashCode ^
      embedModel.hashCode ^
      engineBytes.hashCode ^
      modelBytes.hashCode ^
      embedBytes.hashCode ^
      running.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiStatus &&
          runtimeType == other.runtimeType &&
          dir == other.dir &&
          engine == other.engine &&
          model == other.model &&
          embedModel == other.embedModel &&
          engineBytes == other.engineBytes &&
          modelBytes == other.modelBytes &&
          embedBytes == other.embedBytes &&
          running == other.running;
}

class DescribeProgress {
  /// The character just written up — Dart matches this to its node.
  final String name;
  final String background;
  final int done;
  final int total;
  final String? error;

  const DescribeProgress({
    required this.name,
    required this.background,
    required this.done,
    required this.total,
    this.error,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      background.hashCode ^
      done.hashCode ^
      total.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DescribeProgress &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          background == other.background &&
          done == other.done &&
          total == other.total &&
          error == other.error;
}

class EnrichProgress {
  /// Chapter just processed.
  final int index;
  final String title;

  /// Chapters finished so far in this run / chapters this run set out to do.
  final int done;
  final int total;
  final String? summary;
  final String? error;

  const EnrichProgress({
    required this.index,
    required this.title,
    required this.done,
    required this.total,
    this.summary,
    this.error,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      title.hashCode ^
      done.hashCode ^
      total.hashCode ^
      summary.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrichProgress &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          title == other.title &&
          done == other.done &&
          total == other.total &&
          summary == other.summary &&
          error == other.error;
}

class IndexProgress {
  final int chapter;
  final String title;
  final int done;
  final int total;
  final String? error;

  const IndexProgress({
    required this.chapter,
    required this.title,
    required this.done,
    required this.total,
    this.error,
  });

  @override
  int get hashCode =>
      chapter.hashCode ^
      title.hashCode ^
      done.hashCode ^
      total.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexProgress &&
          runtimeType == other.runtimeType &&
          chapter == other.chapter &&
          title == other.title &&
          done == other.done &&
          total == other.total &&
          error == other.error;
}

class IndexStatus {
  /// Chapters that already carry vectors.
  final int indexed;
  final int total;
  final bool hasModel;

  const IndexStatus({
    required this.indexed,
    required this.total,
    required this.hasModel,
  });

  @override
  int get hashCode => indexed.hashCode ^ total.hashCode ^ hasModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexStatus &&
          runtimeType == other.runtimeType &&
          indexed == other.indexed &&
          total == other.total &&
          hasModel == other.hasModel;
}

/// A landmine the scan knows how to look for. Fixed set, by request: an
/// arbitrary query would have an uncalibrated meaning and no honest way to
/// present its results.
class Landmine {
  final String id;
  final String name;

  /// What the reader is actually asking, in their words.
  final String note;

  const Landmine({required this.id, required this.name, required this.note});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Landmine &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          note == other.note;
}

class RelabelProgress {
  /// The pair just summarized, by name — Dart matches this to its edge.
  final String a;
  final String b;

  /// The prose summary just written (field name kept for the bridge).
  final String label;
  final int done;
  final int total;
  final String? error;

  const RelabelProgress({
    required this.a,
    required this.b,
    required this.label,
    required this.done,
    required this.total,
    this.error,
  });

  @override
  int get hashCode =>
      a.hashCode ^
      b.hashCode ^
      label.hashCode ^
      done.hashCode ^
      total.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelabelProgress &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          label == other.label &&
          done == other.done &&
          total == other.total &&
          error == other.error;
}

/// Where a scan has got to. The work is short but it is not instant — a cold
/// engine can take half a minute to load its weights, and a big book has to be
/// decoded and cut before anything can be read out of it. A screen that says
/// nothing for thirty seconds is indistinguishable from a screen that has hung,
/// which is exactly what it looked like before this existed.
class ScanProgress {
  /// What is happening now, in the reader's words.
  final String phase;

  /// Seconds spent so far in a phase that cannot know its own length; 0 in the
  /// ones that are quick. Nothing here fakes a percentage it does not have.
  final int waited;

  /// Paragraphs being compared, once that number is known.
  final int total;

  /// Set exactly once, on the final event. The scan is over when this arrives.
  final List<SearchHit>? hits;

  const ScanProgress({
    required this.phase,
    required this.waited,
    required this.total,
    this.hits,
  });

  @override
  int get hashCode =>
      phase.hashCode ^ waited.hashCode ^ total.hashCode ^ hits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          waited == other.waited &&
          total == other.total &&
          hits == other.hits;
}

class VetProgress {
  final String name;
  final bool isPerson;
  final int done;
  final int total;
  final String? error;

  const VetProgress({
    required this.name,
    required this.isPerson,
    required this.done,
    required this.total,
    this.error,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isPerson.hashCode ^
      done.hashCode ^
      total.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VetProgress &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isPerson == other.isPerson &&
          done == other.done &&
          total == other.total &&
          error == other.error;
}
