// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `around`, `cache`, `chapter_chunks`, `chapter_excerpt`, `chapter_titles`, `data_dir`, `db_path`, `ensure_loaded`, `is_loaded`, `remember_name`, `remember_person`, `remember_relation`, `residual_people`, `residual_relations`, `scan_cached`, `scan_span`, `snippet`, `store`, `unjudged_names`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Loaded`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Called once at startup with a directory Flutter obtained from the platform.
/// Rust must not guess where an app may write: it differs on every OS, and on
/// Android and iOS it differs per install.
Future<void> initStore({required String dir}) =>
    RustLib.instance.api.crateApiBookInitStore(dir: dir);

Future<CacheUsage> cacheUsage() =>
    RustLib.instance.api.crateApiBookCacheUsage();

/// Throw away every summary and mood for a book. The book, its chapters and the
/// reading progress stay: this deletes the model's opinion, not the reader's.
Future<void> dropSummaries({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookDropSummaries(bookId: bookId);

/// Both, in one go, for the "清空这本书的 AI 数据" button.
Future<void> dropBookCache({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookDropBookCache(bookId: bookId);

/// The reading log. Unlike summaries and vectors this cannot be recomputed, so
/// the button that calls it says so.
Future<void> clearReadingEvents() =>
    RustLib.instance.api.crateApiBookClearReadingEvents();

/// Decode, structure and register a book. Idempotent: opening a book already on
/// the shelf keeps its id, and therefore its progress and its reading history.
Future<BookInfo> openBook({required String path}) =>
    RustLib.instance.api.crateApiBookOpenBook(path: path);

/// Re-parse a book with a user-chosen encoding (`None` returns to detection).
/// The choice persists, so the book decodes correctly on every future open.
Future<BookInfo> setBookEncoding({
  required PlatformInt64 bookId,
  required String path,
  String? encoding,
}) => RustLib.instance.api.crateApiBookSetBookEncoding(
  bookId: bookId,
  path: path,
  encoding: encoding,
);

Future<List<Paragraph>> chapterParagraphs({
  required String path,
  required int index,
}) => RustLib.instance.api.crateApiBookChapterParagraphs(
  path: path,
  index: index,
);

/// Tag every book that has never been tagged, and say how many were.
///
/// Books already on the shelf when this feature landed have no tags, and a book
/// is only tagged when it is decoded — which for an unopened book is never. So
/// the shelf asks for a backfill once on startup. It reads and decodes each
/// untagged file, which is why it runs on the Rust worker pool and not on the
/// way to painting a frame.
Future<int> backfillGenres() =>
    RustLib.instance.api.crateApiBookBackfillGenres();

Future<List<ShelfItem>> listBooks() =>
    RustLib.instance.api.crateApiBookListBooks();

Future<void> saveProgress({
  required PlatformInt64 bookId,
  required PlatformInt64 chapter,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiBookSaveProgress(
  bookId: bookId,
  chapter: chapter,
  offset: offset,
);

Future<List<BookAnnotation>> listAnnotations({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookListAnnotations(bookId: bookId);

Future<PlatformInt64> saveAnnotation({
  PlatformInt64? annotationId,
  required PlatformInt64 bookId,
  required PlatformInt64 chapter,
  required PlatformInt64 start,
  required PlatformInt64 end,
  required String quote,
  required String body,
}) => RustLib.instance.api.crateApiBookSaveAnnotation(
  annotationId: annotationId,
  bookId: bookId,
  chapter: chapter,
  start: start,
  end: end,
  quote: quote,
  body: body,
);

Future<void> deleteAnnotation({
  required PlatformInt64 bookId,
  required PlatformInt64 annotationId,
}) => RustLib.instance.api.crateApiBookDeleteAnnotation(
  bookId: bookId,
  annotationId: annotationId,
);

Future<Int64List> listCompletedChapters({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookListCompletedChapters(bookId: bookId);

Future<void> markChapterCompleted({
  required PlatformInt64 bookId,
  required PlatformInt64 chapter,
}) => RustLib.instance.api.crateApiBookMarkChapterCompleted(
  bookId: bookId,
  chapter: chapter,
);

/// One reading session. Never fabricated: a session with no movement is not
/// written, so the heatmap counts reading, not idling with the app open.
Future<void> logEvent({
  required PlatformInt64 bookId,
  required PlatformInt64 started,
  required PlatformInt64 ended,
  required PlatformInt64 from,
  required PlatformInt64 to,
}) => RustLib.instance.api.crateApiBookLogEvent(
  bookId: bookId,
  started: started,
  ended: ended,
  from: from,
  to: to,
);

/// Sessions since a cutoff, oldest first. The UI buckets them into local days;
/// unix timestamps know no timezone.
Future<List<ReadingEvent>> listEvents({required PlatformInt64 since}) =>
    RustLib.instance.api.crateApiBookListEvents(since: since);

/// Total reading time per book, most-read first.
Future<List<BookTime>> timePerBook() =>
    RustLib.instance.api.crateApiBookTimePerBook();

Future<void> removeBook({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookRemoveBook(bookId: bookId);

/// Delete a book and everything the app ever made of it: chapters, summaries,
/// moods, the semantic index, the reading log, the progress. The `books` row is
/// the root of all of it and the schema cascades, so one DELETE takes the lot.
///
/// The file goes too — but only if it is a file we made. A book downloaded from
/// a source lives in our own books directory and is ours to remove; a TXT the
/// reader imported from their own disk is theirs, sits wherever they keep it,
/// and is not ours to delete no matter what button they pressed in here.
Future<void> deleteBook({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookDeleteBook(bookId: bookId);

/// Change how a book is titled everywhere in the app. The TXT file itself is
/// never touched. An empty (or blank) name clears the override and the title
/// parsed from the file comes back.
Future<void> renameBook({
  required PlatformInt64 bookId,
  required String title,
}) => RustLib.instance.api.crateApiBookRenameBook(bookId: bookId, title: title);

/// Change a book's author everywhere in the app. Like [`rename_book`], the TXT is
/// never touched, and a blank value clears the override so the parsed author
/// returns.
Future<void> setBookAuthor({
  required PlatformInt64 bookId,
  required String author,
}) => RustLib.instance.api.crateApiBookSetBookAuthor(
  bookId: bookId,
  author: author,
);

/// Adopt a chosen image as this book's cover. We copy it into our own data dir
/// rather than referencing it in place, so the cover survives the original being
/// moved or deleted — the same principle as never depending on the TXT's path
/// for anything but reading it.
Future<void> setBookCover({
  required PlatformInt64 bookId,
  required String src,
}) => RustLib.instance.api.crateApiBookSetBookCover(bookId: bookId, src: src);

/// Drop the custom cover and fall back to the generated one, deleting our copy.
Future<void> clearBookCover({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookClearBookCover(bookId: bookId);

/// Pin a book to the top of the shelf, or release it back into recency order.
Future<void> setBookPinned({
  required PlatformInt64 bookId,
  required bool pinned,
}) => RustLib.instance.api.crateApiBookSetBookPinned(
  bookId: bookId,
  pinned: pinned,
);

/// Persist a drag-and-drop ordering of the pinned zone; first id ends on top.
/// Books not in `ids` that were pinned stay pinned — pass the complete zone.
Future<void> setPinOrder({required Int64List ids}) =>
    RustLib.instance.api.crateApiBookSetPinOrder(ids: ids);

Future<void> closeBook({required String path}) =>
    RustLib.instance.api.crateApiBookCloseBook(path: path);

/// Literal search: the words, exactly as typed. No model, no index, nothing to
/// install — it works on a book imported thirty seconds ago.
///
/// Bounded by the same spoiler line as the semantic one: text the reader has not
/// reached is not searched. Finding the murderer's name in chapter 900 by
/// searching for it in chapter 20 is still a spoiler, however it was found.
Future<List<SearchHit>> searchText({
  required String path,
  required String query,
  required PlatformInt64 upToChapter,
  required int k,
}) => RustLib.instance.api.crateApiBookSearchText(
  path: path,
  query: query,
  upToChapter: upToChapter,
  k: k,
);

/// Scan the cast and relationships. Pure rules, no engine, no download —
/// then whatever the model has already ruled on for this book is laid over the
/// top: candidates it rejected are dropped along with their edges, and labels it
/// picked fill in the ones the rules left open.
Future<CastGraph> castGraph({
  required String path,
  required PlatformInt64 bookId,
  required PlatformInt64 upToChapter,
}) => RustLib.instance.api.crateApiBookCastGraph(
  path: path,
  bookId: bookId,
  upToChapter: upToChapter,
);

/// The pre-reading relationship structure always scans the whole available
/// book. It uses the same cached cast pass as the graph, but reads the larger
/// internal roster before the graph UI trims it to ten people.
Future<RelationshipStructureInfo> relationshipStructure({
  required String path,
  required PlatformInt64 bookId,
}) => RustLib.instance.api.crateApiBookRelationshipStructure(
  path: path,
  bookId: bookId,
);

/// Drop the cached graph and every model verdict attached to this book.
Future<void> forgetCast({required PlatformInt64 bookId}) =>
    RustLib.instance.api.crateApiBookForgetCast(bookId: bookId);

class BookAnnotation {
  final PlatformInt64 id;
  final PlatformInt64 bookId;
  final PlatformInt64 chapter;
  final PlatformInt64 start;
  final PlatformInt64 end;
  final String quote;
  final String body;
  final String visibility;
  final String? syncId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const BookAnnotation({
    required this.id,
    required this.bookId,
    required this.chapter,
    required this.start,
    required this.end,
    required this.quote,
    required this.body,
    required this.visibility,
    this.syncId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      chapter.hashCode ^
      start.hashCode ^
      end.hashCode ^
      quote.hashCode ^
      body.hashCode ^
      visibility.hashCode ^
      syncId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookAnnotation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          chapter == other.chapter &&
          start == other.start &&
          end == other.end &&
          quote == other.quote &&
          body == other.body &&
          visibility == other.visibility &&
          syncId == other.syncId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class BookInfo {
  final PlatformInt64 id;
  final String path;
  final String title;
  final String? author;
  final String encoding;
  final String style;
  final PlatformInt64 totalBytes;
  final List<ChapterInfo> chapters;
  final List<VolumeInfo> volumes;
  final int interstitialCount;

  /// Numbering that does not climb. Shown to the user as a hint, never acted on.
  final List<String> anomalies;
  final PlatformInt64 lastChapter;
  final PlatformInt64 lastOffset;
  final String? coverPath;

  /// Coarse, independent estimates. Never percentages: one scene may advance
  /// several lines, and rules cannot honestly measure exact page share.
  final String careerFocus;
  final String romanceFocus;
  final String growthFocus;

  const BookInfo({
    required this.id,
    required this.path,
    required this.title,
    this.author,
    required this.encoding,
    required this.style,
    required this.totalBytes,
    required this.chapters,
    required this.volumes,
    required this.interstitialCount,
    required this.anomalies,
    required this.lastChapter,
    required this.lastOffset,
    this.coverPath,
    required this.careerFocus,
    required this.romanceFocus,
    required this.growthFocus,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      author.hashCode ^
      encoding.hashCode ^
      style.hashCode ^
      totalBytes.hashCode ^
      chapters.hashCode ^
      volumes.hashCode ^
      interstitialCount.hashCode ^
      anomalies.hashCode ^
      lastChapter.hashCode ^
      lastOffset.hashCode ^
      coverPath.hashCode ^
      careerFocus.hashCode ^
      romanceFocus.hashCode ^
      growthFocus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          author == other.author &&
          encoding == other.encoding &&
          style == other.style &&
          totalBytes == other.totalBytes &&
          chapters == other.chapters &&
          volumes == other.volumes &&
          interstitialCount == other.interstitialCount &&
          anomalies == other.anomalies &&
          lastChapter == other.lastChapter &&
          lastOffset == other.lastOffset &&
          coverPath == other.coverPath &&
          careerFocus == other.careerFocus &&
          romanceFocus == other.romanceFocus &&
          growthFocus == other.growthFocus;
}

class BookTime {
  final String title;
  final PlatformInt64 seconds;

  const BookTime({required this.title, required this.seconds});

  @override
  int get hashCode => title.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookTime &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          seconds == other.seconds;
}

/// What one book has cost us in AI output, and what deleting it would win back.
class CacheEntry {
  final PlatformInt64 bookId;
  final String title;
  final PlatformInt64 chapterCount;

  /// Chapters that carry a summary — the enrichment pass is resumable, so this
  /// is routinely less than the whole book.
  final PlatformInt64 summaries;
  final PlatformInt64 summaryBytes;
  final PlatformInt64 chunks;
  final PlatformInt64 chunkBytes;

  const CacheEntry({
    required this.bookId,
    required this.title,
    required this.chapterCount,
    required this.summaries,
    required this.summaryBytes,
    required this.chunks,
    required this.chunkBytes,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      chapterCount.hashCode ^
      summaries.hashCode ^
      summaryBytes.hashCode ^
      chunks.hashCode ^
      chunkBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheEntry &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          chapterCount == other.chapterCount &&
          summaries == other.summaries &&
          summaryBytes == other.summaryBytes &&
          chunks == other.chunks &&
          chunkBytes == other.chunkBytes;
}

class CacheUsage {
  final List<CacheEntry> books;

  /// The whole library file, which holds the rows above plus the chapter cut,
  /// the reading log and the settings. Always bigger than the sum of the parts.
  final PlatformInt64 dbBytes;

  const CacheUsage({required this.books, required this.dbBytes});

  @override
  int get hashCode => books.hashCode ^ dbBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheUsage &&
          runtimeType == other.runtimeType &&
          books == other.books &&
          dbBytes == other.dbBytes;
}

class CastGraph {
  final List<CastPerson> people;
  final List<CastRelation> edges;

  /// Chapters actually scanned — the spoiler cap — so the UI can say "up to
  /// chapter N" instead of implying it read the whole book.
  final int upto;

  const CastGraph({
    required this.people,
    required this.edges,
    required this.upto,
  });

  @override
  int get hashCode => people.hashCode ^ edges.hashCode ^ upto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CastGraph &&
          runtimeType == other.runtimeType &&
          people == other.people &&
          edges == other.edges &&
          upto == other.upto;
}

class CastPerson {
  final String name;

  /// Shorter forms folded in (吕小鱼 ← 小鱼).
  final List<String> aliases;
  final int mentions;

  /// Distinct chapters the person appears in, within the scanned range.
  final int chapters;
  final int firstChapter;

  /// The statistics could not tell whether this is a person; the model has not
  /// ruled on it yet. Shown dimmed, and it is what 校对人物 asks about.
  final bool uncertain;

  /// The model's prose account of who this character is, or None until it has
  /// written one. Every UI must render correctly when this is None.
  final String? background;

  /// The sentences that account rests on — shown to the reader, so a claim
  /// about a character can always be traced back to the book.
  final List<RelEvidence> evidence;

  const CastPerson({
    required this.name,
    required this.aliases,
    required this.mentions,
    required this.chapters,
    required this.firstChapter,
    required this.uncertain,
    this.background,
    required this.evidence,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      aliases.hashCode ^
      mentions.hashCode ^
      chapters.hashCode ^
      firstChapter.hashCode ^
      uncertain.hashCode ^
      background.hashCode ^
      evidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CastPerson &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          aliases == other.aliases &&
          mentions == other.mentions &&
          chapters == other.chapters &&
          firstChapter == other.firstChapter &&
          uncertain == other.uncertain &&
          background == other.background &&
          evidence == other.evidence;
}

class CastRelation {
  /// Indices into [`CastGraph::people`].
  final int a;
  final int b;

  /// Sharing a sentence counts double sharing a paragraph.
  final int weight;

  /// The model's prose summary of how the pair get on, or None until it has
  /// written one. (Field kept named `label` to avoid a bridge regeneration; it
  /// carries a sentence now, not a category.)
  final String? label;

  /// Pre-formatted appellation chips ("同学×5"), for the evidence panel.
  final List<String> hints;
  final List<RelEvidence> evidence;

  const CastRelation({
    required this.a,
    required this.b,
    required this.weight,
    this.label,
    required this.hints,
    required this.evidence,
  });

  @override
  int get hashCode =>
      a.hashCode ^
      b.hashCode ^
      weight.hashCode ^
      label.hashCode ^
      hints.hashCode ^
      evidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CastRelation &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          weight == other.weight &&
          label == other.label &&
          hints == other.hints &&
          evidence == other.evidence;
}

class ChapterInfo {
  final int index;

  /// What the author numbered it. Absent, repeated, and out of order in real
  /// books, so never use it as a key — `index` is the key.
  final PlatformInt64? number;
  final String title;
  final PlatformInt64 start;
  final PlatformInt64 end;

  /// One-sentence summary written by the enrichment pass, if it has reached
  /// this chapter. Every UI must render correctly when this is None.
  final String? summary;

  /// One-word mood label from the same pass, from a fixed vocabulary. Same
  /// rule: absent until enrichment has been here, and absence must render fine.
  final String? mood;

  const ChapterInfo({
    required this.index,
    this.number,
    required this.title,
    required this.start,
    required this.end,
    this.summary,
    this.mood,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      number.hashCode ^
      title.hashCode ^
      start.hashCode ^
      end.hashCode ^
      summary.hashCode ^
      mood.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          number == other.number &&
          title == other.title &&
          start == other.start &&
          end == other.end &&
          summary == other.summary &&
          mood == other.mood;
}

enum ParaKind {
  body,
  title,

  /// A volume header. Divides the story; belongs to no chapter.
  volume,

  /// Author's note or site ad. Rendered, but set apart, and never in the TOC.
  interstitial,
}

class Paragraph {
  final ParaKind kind;
  final String text;

  /// Byte offsets into the decoded book. Reading progress, bookmarks and
  /// highlights anchor to these — not to paragraph indices, which move
  /// whenever segmentation improves.
  final PlatformInt64 start;
  final PlatformInt64 end;

  const Paragraph({
    required this.kind,
    required this.text,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ text.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Paragraph &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          start == other.start &&
          end == other.end;
}

class ReadingEvent {
  final PlatformInt64 bookId;
  final PlatformInt64 started;
  final PlatformInt64 ended;

  const ReadingEvent({
    required this.bookId,
    required this.started,
    required this.ended,
  });

  @override
  int get hashCode => bookId.hashCode ^ started.hashCode ^ ended.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingEvent &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          started == other.started &&
          ended == other.ended;
}

class RelEvidence {
  final int chapter;
  final String text;

  const RelEvidence({required this.chapter, required this.text});

  @override
  int get hashCode => chapter.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelEvidence &&
          runtimeType == other.runtimeType &&
          chapter == other.chapter &&
          text == other.text;
}

class RelationshipEvidenceInfo {
  final int chapter;
  final String person;
  final String kind;
  final String text;

  const RelationshipEvidenceInfo({
    required this.chapter,
    required this.person,
    required this.kind,
    required this.text,
  });

  @override
  int get hashCode =>
      chapter.hashCode ^ person.hashCode ^ kind.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationshipEvidenceInfo &&
          runtimeType == other.runtimeType &&
          chapter == other.chapter &&
          person == other.person &&
          kind == other.kind &&
          text == other.text;
}

class RelationshipPersonInfo {
  final String name;
  final String status;
  final List<RelationshipEvidenceInfo> evidence;

  const RelationshipPersonInfo({
    required this.name,
    required this.status,
    required this.evidence,
  });

  @override
  int get hashCode => name.hashCode ^ status.hashCode ^ evidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationshipPersonInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          evidence == other.evidence;
}

class RelationshipStructureInfo {
  final String label;
  final String reason;
  final int confidence;
  final String protagonist;
  final int analyzedChapters;
  final int candidateCount;
  final List<RelationshipPersonInfo> people;
  final List<RelationshipEvidenceInfo> groupEvidence;

  const RelationshipStructureInfo({
    required this.label,
    required this.reason,
    required this.confidence,
    required this.protagonist,
    required this.analyzedChapters,
    required this.candidateCount,
    required this.people,
    required this.groupEvidence,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      reason.hashCode ^
      confidence.hashCode ^
      protagonist.hashCode ^
      analyzedChapters.hashCode ^
      candidateCount.hashCode ^
      people.hashCode ^
      groupEvidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationshipStructureInfo &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          reason == other.reason &&
          confidence == other.confidence &&
          protagonist == other.protagonist &&
          analyzedChapters == other.analyzedChapters &&
          candidateCount == other.candidateCount &&
          people == other.people &&
          groupEvidence == other.groupEvidence;
}

/// One place in the book, found by either search. `score` is 1.0 for a literal
/// match — it either says the words or it does not — and the cosine for a
/// semantic one.
class SearchHit {
  final int chapter;
  final String title;

  /// Byte offset in the decoded text: where the reader is sent.
  final PlatformInt64 start;
  final String text;
  final double score;

  const SearchHit({
    required this.chapter,
    required this.title,
    required this.start,
    required this.text,
    required this.score,
  });

  @override
  int get hashCode =>
      chapter.hashCode ^
      title.hashCode ^
      start.hashCode ^
      text.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          chapter == other.chapter &&
          title == other.title &&
          start == other.start &&
          text == other.text &&
          score == other.score;
}

/// What the shelf shows. Deliberately not `BookInfo`: the shelf must not pay for
/// 1500 chapter titles per book.
class ShelfItem {
  final PlatformInt64 id;
  final String path;
  final String title;
  final String? author;
  final PlatformInt64 chapterCount;
  final PlatformInt64 lastChapter;
  final PlatformInt64 lastOffset;
  final PlatformInt64 totalBytes;
  final PlatformInt64? lastOpenedAt;

  /// What the file decoded as, so the user can tell a wrong guess at a glance.
  final String encoding;

  /// Stable per title, so a book keeps its cover colour forever.
  final int coverHue;

  /// The chapter the reader stopped in. Empty for a book never opened.
  final String lastChapterTitle;

  /// Pinned books hold the top of the shelf, above recency.
  final bool pinned;

  /// 类型标签 (玄幻, 都市…), at most two. Empty when the text does not say, or
  /// when the book has not been decoded yet — it is computed on first open,
  /// and it is a lexicon, not a model: no engine, no download, no waiting.
  final List<String> genreTags;

  /// A reader-chosen cover image on disk. None means show the generated cover.
  final String? coverPath;

  const ShelfItem({
    required this.id,
    required this.path,
    required this.title,
    this.author,
    required this.chapterCount,
    required this.lastChapter,
    required this.lastOffset,
    required this.totalBytes,
    this.lastOpenedAt,
    required this.encoding,
    required this.coverHue,
    required this.lastChapterTitle,
    required this.pinned,
    required this.genreTags,
    this.coverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      author.hashCode ^
      chapterCount.hashCode ^
      lastChapter.hashCode ^
      lastOffset.hashCode ^
      totalBytes.hashCode ^
      lastOpenedAt.hashCode ^
      encoding.hashCode ^
      coverHue.hashCode ^
      lastChapterTitle.hashCode ^
      pinned.hashCode ^
      genreTags.hashCode ^
      coverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShelfItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          author == other.author &&
          chapterCount == other.chapterCount &&
          lastChapter == other.lastChapter &&
          lastOffset == other.lastOffset &&
          totalBytes == other.totalBytes &&
          lastOpenedAt == other.lastOpenedAt &&
          encoding == other.encoding &&
          coverHue == other.coverHue &&
          lastChapterTitle == other.lastChapterTitle &&
          pinned == other.pinned &&
          genreTags == other.genreTags &&
          coverPath == other.coverPath;
}

class VolumeInfo {
  final String title;
  final int firstChapter;

  const VolumeInfo({required this.title, required this.firstChapter});

  @override
  int get hashCode => title.hashCode ^ firstChapter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VolumeInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          firstChapter == other.firstChapter;
}
