// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `books_dir`, `load`, `parse`, `with_store`, `write_book`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Import a legado export — one sheet or a thousand. Returns how many landed.
/// Their rules are stored verbatim: we keep the user's file, not our reading of
/// it, because the format has corners we do not implement and dropping them
/// would quietly damage a sheet that works elsewhere.
Future<int> importSources({required String json}) =>
    RustLib.instance.api.crateApiSourceImportSources(json: json);

/// The same, from a link — which is how rule sheets actually circulate.
Future<int> importSourcesFromUrl({required String url}) =>
    RustLib.instance.api.crateApiSourceImportSourcesFromUrl(url: url);

Future<List<SourceItem>> listSources() =>
    RustLib.instance.api.crateApiSourceListSources();

Future<void> setSourceEnabled({required String url, required bool enabled}) =>
    RustLib.instance.api.crateApiSourceSetSourceEnabled(
      url: url,
      enabled: enabled,
    );

Future<void> deleteSource({required String url}) =>
    RustLib.instance.api.crateApiSourceDeleteSource(url: url);

/// Delete a batch — however the manager happened to have them filtered. Returns
/// how many rows actually went.
Future<int> deleteSources({required List<String> urls}) =>
    RustLib.instance.api.crateApiSourceDeleteSources(urls: urls);

Future<int> deleteAllSources() =>
    RustLib.instance.api.crateApiSourceDeleteAllSources();

/// Take a source to the live site and see whether it is dead. It is dead if the
/// site will not talk to us, or if the sheet needs something we refuse to run;
/// anything short of that, it keeps its place. See `source::TestResult`.
///
/// There is deliberately no keyword to pass. Whether a source can find *one
/// particular book* is not the question, so the words it is asked are the
/// engine's business (`source::TEST_KEYS`), not a setting: letting the caller
/// pick the word is exactly how a source that stocks no wuxia gets recorded as
/// broken.
Future<SourceTest> testSource({required String url}) =>
    RustLib.instance.api.crateApiSourceTestSource(url: url);

Future<void> cancelTests() => RustLib.instance.api.crateApiSourceCancelTests();

/// Validate the whole list, many sites at once.
///
/// A legado export is not a handful of sources, it is thousands, and most of
/// them are dead. Testing them one after another means an afternoon of waiting,
/// so this fans out and streams verdicts as they land — and each verdict is
/// written to the database the moment it arrives, so closing the page costs you
/// nothing but the sources still in flight.
///
/// `only_untested` is the default because the list is long and re-proving the
/// sources that already work is how you turn ten minutes into an hour.
Stream<TestFeed> testSources({required bool onlyUntested}) =>
    RustLib.instance.api.crateApiSourceTestSources(onlyUntested: onlyUntested);

Future<void> cancelSearch() =>
    RustLib.instance.api.crateApiSourceCancelSearch();

/// Search every enabled source at once. Sources answer at wildly different
/// speeds and some never answer at all, so results stream: the first site to
/// come back is on screen while the slow ones are still dialling.
///
/// `exact` throws away every hit whose title is not the word you typed. It is a
/// filter on the answers, not a different question: these sites have no exact-
/// match mode, and half of them return their whole catalogue for a short word.
Stream<SearchFeed> searchSources({required String key, required bool exact}) =>
    RustLib.instance.api.crateApiSourceSearchSources(key: key, exact: exact);

Future<void> cancelProbe() => RustLib.instance.api.crateApiSourceCancelProbe();

/// Open every site's copy of one book and report how long it is and whether it
/// can be read. Results stream: the fast sites are on screen while the slow ones
/// are still counting.
Stream<OfferProbe> probeOffers({required List<Offer> offers}) =>
    RustLib.instance.api.crateApiSourceProbeOffers(offers: offers);

Future<void> cancelDownload() =>
    RustLib.instance.api.crateApiSourceCancelDownload();

/// Fetch a whole book and write it as one TXT. Chapters are fetched a few at a
/// time — enough to not take an hour, few enough to not hammer a stranger's
/// server — and written strictly in order, because the file *is* the book and
/// its byte offsets are what every other feature anchors to.
Stream<DownloadProgress> downloadBook({
  required String sourceUrl,
  required String bookUrl,
  required String title,
  required String author,
}) => RustLib.instance.api.crateApiSourceDownloadBook(
  sourceUrl: sourceUrl,
  bookUrl: bookUrl,
  title: title,
  author: author,
);

class DownloadProgress {
  final String phase;
  final int done;
  final int total;

  /// Chapters the site would not give us. A handful is normal; a lot means the
  /// source is bad and the book will have holes — the UI says so rather than
  /// pretending the download succeeded.
  final int failed;

  /// Set exactly once, on the final event: the TXT that is now on disk.
  final String? path;

  const DownloadProgress({
    required this.phase,
    required this.done,
    required this.total,
    required this.failed,
    this.path,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      done.hashCode ^
      total.hashCode ^
      failed.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          done == other.done &&
          total == other.total &&
          failed == other.failed &&
          path == other.path;
}

class FoundBookItem {
  final String sourceUrl;
  final String sourceName;
  final String name;
  final String author;
  final String kind;
  final String wordCount;
  final String lastChapter;
  final String intro;
  final String bookUrl;

  const FoundBookItem({
    required this.sourceUrl,
    required this.sourceName,
    required this.name,
    required this.author,
    required this.kind,
    required this.wordCount,
    required this.lastChapter,
    required this.intro,
    required this.bookUrl,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^
      sourceName.hashCode ^
      name.hashCode ^
      author.hashCode ^
      kind.hashCode ^
      wordCount.hashCode ^
      lastChapter.hashCode ^
      intro.hashCode ^
      bookUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FoundBookItem &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          sourceName == other.sourceName &&
          name == other.name &&
          author == other.author &&
          kind == other.kind &&
          wordCount == other.wordCount &&
          lastChapter == other.lastChapter &&
          intro == other.intro &&
          bookUrl == other.bookUrl;
}

/// One site's offer of one book: everything needed to go and measure it.
class Offer {
  final String sourceUrl;
  final String bookUrl;

  const Offer({required this.sourceUrl, required this.bookUrl});

  @override
  int get hashCode => sourceUrl.hashCode ^ bookUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Offer &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          bookUrl == other.bookUrl;
}

/// What a site is really offering, found out by opening the book.
///
/// Search results lie by omission. Every site says it has 《异兽迷城》; one has
/// 1303 chapters of clean prose, the next has a 50-chapter abridgement whose
/// text is ciphertext only a browser can decrypt. Nothing in the search result
/// distinguishes them — you have to open the table of contents and read a
/// chapter, which is exactly what this does.
class OfferProbe {
  final String sourceUrl;
  final int chapters;
  final String lastTitle;

  /// Did a chapter of actual prose come back? A big table of contents in front
  /// of unreadable text is worth nothing, and must not win the comparison.
  final bool readable;

  /// Empty when all is well; otherwise why this source is a bad bet.
  final String note;

  const OfferProbe({
    required this.sourceUrl,
    required this.chapters,
    required this.lastTitle,
    required this.readable,
    required this.note,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^
      chapters.hashCode ^
      lastTitle.hashCode ^
      readable.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfferProbe &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          chapters == other.chapters &&
          lastTitle == other.lastTitle &&
          readable == other.readable &&
          note == other.note;
}

/// Results as they land, source by source, plus how far along we are.
class SearchFeed {
  final int done;
  final int total;

  /// Which source just answered — the label under the progress bar.
  final String sourceName;
  final List<FoundBookItem> hits;

  const SearchFeed({
    required this.done,
    required this.total,
    required this.sourceName,
    required this.hits,
  });

  @override
  int get hashCode =>
      done.hashCode ^ total.hashCode ^ sourceName.hashCode ^ hits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchFeed &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total &&
          sourceName == other.sourceName &&
          hits == other.hits;
}

/// A rule sheet as the manager shows it.
class SourceItem {
  final String url;
  final String name;
  final String group;
  final bool enabled;

  /// None = never tested. False = validation ruled it out for good. True = it
  /// survived — which means "not known to be dead", not "proved to work".
  final bool? ok;
  final String note;

  const SourceItem({
    required this.url,
    required this.name,
    required this.group,
    required this.enabled,
    this.ok,
    required this.note,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      name.hashCode ^
      group.hashCode ^
      enabled.hashCode ^
      ok.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceItem &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          name == other.name &&
          group == other.group &&
          enabled == other.enabled &&
          ok == other.ok &&
          note == other.note;
}

class SourceTest {
  final String url;
  final bool ok;
  final String message;

  const SourceTest({
    required this.url,
    required this.ok,
    required this.message,
  });

  @override
  int get hashCode => url.hashCode ^ ok.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceTest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          ok == other.ok &&
          message == other.message;
}

/// How a whole-list validation is going, as it goes.
class TestFeed {
  final int done;
  final int total;
  final int ok;
  final int failed;

  /// The source that just answered, and what it said.
  final String sourceName;
  final String message;

  const TestFeed({
    required this.done,
    required this.total,
    required this.ok,
    required this.failed,
    required this.sourceName,
    required this.message,
  });

  @override
  int get hashCode =>
      done.hashCode ^
      total.hashCode ^
      ok.hashCode ^
      failed.hashCode ^
      sourceName.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TestFeed &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total &&
          ok == other.ok &&
          failed == other.failed &&
          sourceName == other.sourceName &&
          message == other.message;
}
